/**
 * KSDAS IT DEL - Master Seed Data
 * Kerja Sama Data & Analytics System - Institut Teknologi Del
 * Version: 0.2
 */

window.KSDAS_SEED_DATA = {
  version: "0.2.0",
  lastUpdated: "2026-10-03T01:00:00Z",
  institution: {
    name: "Institut Teknologi Del",
    shortName: "IT Del",
    campus: "Sitoluama, Laguboti, Kabupaten Toba, Sumatera Utara",
    website: "https://www.del.ac.id"
  },
  roles: [
    { id: "ADMIN_STAFF", name: "Staff Unit Kerja Sama", level: 1, permissions: ["create", "upload", "edit", "validate", "delete", "master_edit", "export"] },
    { id: "BUREAU_HEAD", name: "Kepala Biro Kemitraan", level: 2, permissions: ["review", "validate", "edit_auth", "monitor", "export", "reports"] },
    { id: "WR3", name: "Wakil Rektor III (Kemitraan)", level: 3, permissions: ["review", "validate", "monitor", "executive_analytics", "export", "reports"] },
    { id: "EXECUTIVE_VIEWER", name: "Rektor / Dekan", level: 4, permissions: ["view", "download", "filter", "reports"] },
    { id: "QUALITY_REVIEWER", name: "SPM (Satuan Penjaminan Mutu)", level: 4, permissions: ["view", "download", "filter", "accreditation_edit", "evidence_verify", "reports"] },
    { id: "FACULTY_VIEWER", name: "Pengelola Fakultas", level: 5, permissions: ["view_faculty", "filter", "download", "add_activity"] },
    { id: "PROGRAM_VIEWER", name: "Pengelola Program Studi", level: 5, permissions: ["view_program", "filter", "download", "add_evidence"] },
    { id: "UNIT_VIEWER", name: "Pengelola Unit Internal", level: 5, permissions: ["view_unit", "filter", "download"] }
  ],
  faculties: [
    { id: "FITE", code: "FITE", name: "Fakultas Informatika dan Teknik Elektro", dean: "Dr. Johannes Harungguan Sianipar, S.T., M.T." },
    { id: "FTI", code: "FTI", name: "Fakultas Teknologi Industri", dean: "Dr. Rizal Sinaga, S.T., M.T." },
    { id: "FB", code: "FB", name: "Fakultas Bioteknologi", dean: "Dr. Merry M. Sibarani, S.Si., M.Si." }
  ],
  studyPrograms: [
    { id: "PRODI-IF", facultyId: "FITE", code: "S1-IF", name: "S1 Informatika", kaprodi: "Yusuf Kurniawan, S.T., M.Sc." },
    { id: "PRODI-SI", facultyId: "FITE", code: "S1-SI", name: "S1 Sistem Informasi", kaprodi: "Tengku M. Khairil, S.Kom., M.Kom." },
    { id: "PRODI-TE", facultyId: "FITE", code: "S1-TE", name: "S1 Teknik Elektro", kaprodi: "Indra H. M. Saragih, S.T., M.T." },
    { id: "PRODI-TRPL", facultyId: "FITE", code: "D4-TRPL", name: "D4 Teknologi Rekayasa Perangkat Lunak", kaprodi: "Ronal M. Panjaitan, S.Kom., M.T." },
    { id: "PRODI-TI", facultyId: "FITE", code: "D3-TI", name: "D3 Teknologi Informasi", kaprodi: "Nenni A. Tampubolon, S.Kom., M.Kom." },
    { id: "PRODI-TK", facultyId: "FITE", code: "D3-TK", name: "D3 Teknologi Komputer", kaprodi: "Albertus S. Silalahi, S.T., M.T." },
    { id: "PRODI-MR", facultyId: "FTI", code: "S1-MR", name: "S1 Manajemen Rekayasa", kaprodi: "Yanti N. Simamora, S.T., M.Sc." },
    { id: "PRODI-MT", facultyId: "FTI", code: "S1-MT", name: "S1 Teknik Metalurgi", kaprodi: "David H. Marpaung, S.T., M.T." },
    { id: "PRODI-BP", facultyId: "FB", code: "S1-BP", name: "S1 Teknik Bioproses", kaprodi: "Maria P. Hutapea, S.Si., M.Biotech." }
  ],
  internalUnits: [
    { id: "UNIT-KERJASAMA", code: "UKS", name: "Unit Kerja Sama & Hubungan Alumni", head: "Humasak T. A. Simanjuntak, S.T., M.ISD." },
    { id: "UNIT-SDI", code: "SDI", name: "Direktorat Sistem & Data Informasi (SDI/TSI)", head: "Gindo P. Sibuea, S.Kom., M.Kom." },
    { id: "UNIT-SPM", code: "SPM", name: "Satuan Penjaminan Mutu", head: "Dr. Arnaldo Sinaga (Ex-officio)" },
    { id: "UNIT-LPPM", code: "LPPM", name: "Lembaga Penelitian dan Pengabdian Masyarakat", head: "Dr. Fitriani Saragih, S.T., M.T." },
    { id: "UNIT-CDC", code: "CDC", name: "Career Development Center & Kemahasiswaan", head: "Monika Siahaan, S.Sos." },
    { id: "UNIT-BAAK", code: "BAAK", name: "Biro Administrasi Akademik & Kemahasiswaan", head: "Binsar Siregar, S.Si." }
  ],
  triDharmaTypes: [
    { id: "EDUCATION", code: "PENDIDIKAN", name: "Pendidikan & Pengajaran", description: "Magang MBKM, Kuliah Tamu, Kurikulum Industri, Beasiswa" },
    { id: "RESEARCH", code: "PENELITIAN", name: "Penelitian, Pengembangan & Inovasi", description: "Joint Research, Publikasi Ilmiah, Hibah Riset Bersama, Paten" },
    { id: "COMMUNITY_SERVICE", code: "PENGMAS", name: "Pengabdian kepada Masyarakat", description: "Digitalisasi Desa Wisata, Pendampingan UMKM Toba, Pelatihan Guru" },
    { id: "INSTITUTIONAL", code: "TATA_KELOLA", name: "Pengembangan Institusi & Fasilitas", description: "Donasi Laboratorium, Infrastruktur Jaringan, Benchmarking" }
  ],
  partners: [
    {
      id: "PARTNER-001",
      name: "PT Huawei Tech Investment",
      code: "HUAWEI",
      type: "INDUSTRY",
      category: "MULTINATIONAL",
      country: "Indonesia / China",
      city: "Jakarta Selatan",
      address: "Wisma Mulia 2 Lt. 28, Jl. Jend. Gatot Subroto No. 42",
      contactPerson: "Budi Santoso, Ph.D. (Director of ICT Talent Ecosystem)",
      email: "budi.santoso@huawei.com",
      phone: "+62 21 5296 3888",
      website: "https://www.huawei.com/id",
      status: "ACTIVE",
      totalAgreements: 3,
      verifiedDate: "2024-01-15",
      notes: "Mitra strategis pendirian Huawei ICT Academy dan Cloud Computing Lab di IT Del."
    },
    {
      id: "PARTNER-002",
      name: "PT Astra International Tbk",
      code: "ASTRA",
      type: "INDUSTRY",
      category: "CONGLOMERATE",
      country: "Indonesia",
      city: "Jakarta Utara",
      address: "Menara Astra, Jl. Jend. Sudirman Kav. 5-6",
      contactPerson: "Ratna Sari Dewi (Head of CSR & Education Support)",
      email: "csr.edu@astra.co.id",
      phone: "+62 21 6522 555",
      website: "https://www.astra.co.id",
      status: "ACTIVE",
      totalAgreements: 4,
      verifiedDate: "2023-08-10",
      notes: "Sponsor beasiswa prestasi, hibah alat lab rekayasa, dan perekrutan lulusan."
    },
    {
      id: "PARTNER-003",
      name: "PT Microsoft Indonesia",
      code: "MICROSOFT",
      type: "INDUSTRY",
      category: "MULTINATIONAL",
      country: "Indonesia / USA",
      city: "Jakarta Pusat",
      address: "Indonesia Stock Exchange Building Tower II, 18th Floor",
      contactPerson: "Dian Astuti (Education Industry Lead)",
      email: "dian.astuti@microsoft.com",
      phone: "+62 21 2551 8100",
      website: "https://www.microsoft.com/id-id",
      status: "ACTIVE",
      totalAgreements: 2,
      verifiedDate: "2025-02-14",
      notes: "Kerja sama AI for Education, Azure Cloud Credits untuk riset mahasiswa, dan sertifikasi Microsoft Certified Associate."
    },
    {
      id: "PARTNER-004",
      name: "PT Bank Mandiri (Persero) Tbk",
      code: "MANDIRI",
      type: "BUMN",
      category: "FINANCIAL_SERVICES",
      country: "Indonesia",
      city: "Jakarta Selatan",
      address: "Plaza Mandiri, Jl. Jend. Gatot Subroto Kav. 36-38",
      contactPerson: "Hendra Wijaya (VP Corporate Secretary / TJSL)",
      email: "tjsl@bankmandiri.co.id",
      phone: "+62 21 526 5045",
      website: "https://www.bankmandiri.co.id",
      status: "ACTIVE",
      totalAgreements: 3,
      verifiedDate: "2024-05-19",
      notes: "Digital banking student ecosystem, program magang bersertifikat, dan renovasi co-working space IT Del."
    },
    {
      id: "PARTNER-005",
      name: "Institut Teknologi Bandung",
      code: "ITB",
      type: "UNIVERSITY",
      category: "STATE_UNIVERSITY",
      country: "Indonesia",
      city: "Bandung",
      address: "Jl. Ganesa No. 10, Coblong",
      contactPerson: "Prof. Ir. Taufiq Hidayat (Direktur Kemitraan)",
      email: "kemitraan@itb.ac.id",
      phone: "+62 22 250 0935",
      website: "https://www.itb.ac.id",
      status: "ACTIVE",
      totalAgreements: 4,
      verifiedDate: "2023-01-20",
      notes: "Program bimbingan riset bersama, pertukaran dosen, dan fast-track program magister."
    },
    {
      id: "PARTNER-006",
      name: "Pemerintah Kabupaten Toba",
      code: "PEMKAB-TOBA",
      type: "GOVERNMENT",
      category: "REGIONAL_GOVERNMENT",
      country: "Indonesia",
      city: "Balige",
      address: "Jl. Sutomo No. 1, Balige, Kabupaten Toba",
      contactPerson: "Sekretaris Daerah Kab. Toba",
      email: "diskominfo@tobakab.go.id",
      phone: "+62 632 21100",
      website: "https://tobakab.go.id",
      status: "ACTIVE",
      totalAgreements: 3,
      verifiedDate: "2024-03-01",
      notes: "Kolaborasi Smart City Toba, sistem informasi pariwisata Danau Toba, dan pelatihan UMKM kriya ulos."
    },
    {
      id: "PARTNER-007",
      name: "National University of Singapore",
      code: "NUS",
      type: "UNIVERSITY",
      category: "INTERNATIONAL",
      country: "Singapura",
      city: "Singapore",
      address: "21 Lower Kent Ridge Rd",
      contactPerson: "Dr. Kevin Tan (Global Relations Officer)",
      email: "gro@nus.edu.sg",
      phone: "+65 6516 6666",
      website: "https://www.nus.edu.sg",
      status: "ACTIVE",
      totalAgreements: 2,
      verifiedDate: "2024-09-12",
      notes: "Pertukaran mahasiswa skala internasional (STEER program) dan workshop riset bioinformatika."
    },
    {
      id: "PARTNER-008",
      name: "Yayasan Inovasi Teknologi Toba Lestari",
      code: "YITTL",
      type: "NGO",
      category: "FOUNDATION",
      country: "Indonesia",
      city: "Laguboti",
      address: "Jl. Pematang Siantar KM 11",
      contactPerson: "Martua Simatupang",
      email: "info@tobalestari.org",
      phone: "+62 632 33120",
      website: "https://tobalestari.org",
      status: "INACTIVE",
      totalAgreements: 1,
      verifiedDate: "2023-04-10",
      notes: "Perlu follow up tindak lanjut pembaruan MoU yang habis masa berlaku akhir 2025."
    }
  ],
  documents: [
    {
      id: "DOC-MOU-2024-001",
      documentNumber: "012/ITDel/MoU/IV/2024",
      title: "Nota Kesepahaman tentang Pengembangan Sumber Daya Manusia dan Transformasi Digital ICT",
      type: "MOU_LOI",
      partnerId: "PARTNER-001",
      partnerName: "PT Huawei Tech Investment",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Guo Hai (Director of Enterprise Business)",
      partnerSignatoryPosition: "Director of Enterprise Business Group",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2024-04-18",
      effectiveStartDate: "2024-04-18",
      effectiveEndDate: "2028-04-17",
      scope: "Penyelenggaraan Huawei Authorized Information and Network Academy (HAINA), kurikulum sertifikasi industri 5G & Cloud, dan beasiswa pelatihan talenta digital.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Huawei ICT Academy & Pelatihan Sertifikasi Cloud HCIA",
      pic: "Ronal M. Panjaitan, S.Kom., M.T.",
      location: "Kampus IT Del, Laguboti",
      participantCount: 150,
      budget: 350000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "Laboratorium ICT Academy terakreditasi dan 100 mahasiswa lulus sertifikasi HCIA Cloud/Routing.",
      expectedOutcome: "Peningkatan daya saing lulusan FITE di kancah industri telekomunikasi nasional.",
      actualOutput: "128 mahasiswa terlatih, 85 tersertifikasi HCIA pada tahun pertama.",
      outcome: "92% lulusan terserap kerja < 3 bulan setelah wisuda.",
      impact: "Mendongkrak peringkat akreditasi IAPS FITE menuju akreditasi UNGGUL.",
      followUp: "Pelaksanaan kelas reguler semester ganjil dan workshop instruktur bersertifikat.",
      status: "VALIDATED",
      confidenceScore: 0.98,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 4,
      batchId: "SEED-BATCH-01",
      extractedDate: "2024-04-19T08:12:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-04-20T10:30:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_Huawei_ITDel_2024.pdf",
      fileName: "MOU_Huawei_ITDel_2024.pdf",
      fileSize: "2.4 MB"
    },
    {
      id: "DOC-PKS-2024-002",
      documentNumber: "028/ITDel/PKS/FITE/VI/2024",
      title: "Perjanjian Kerja Sama Pendirian Huawei ICT Academy dan Fasilitasi Ujian Sertifikasi HCIA Mahasiswa",
      type: "PKS_MOA",
      partnerId: "PARTNER-001",
      partnerName: "PT Huawei Tech Investment",
      parentId: "DOC-MOU-2024-001",
      parentNumber: "012/ITDel/MoU/IV/2024",
      country: "Indonesia",
      partnerSignatoryName: "Budi Santoso, Ph.D.",
      partnerSignatoryPosition: "Director of ICT Talent Ecosystem",
      itDelSignatoryName: "Dr. Johannes Harungguan Sianipar, S.T., M.T.",
      itDelSignatoryPosition: "Dekan Fakultas Informatika dan Teknik Elektro",
      signedDate: "2024-06-10",
      effectiveStartDate: "2024-06-10",
      effectiveEndDate: "2027-06-09",
      scope: "Fasilitasi platform pembelajaran digital Huawei Talent Online, voucher ujian sertifikasi internasional untuk 200 mahasiswa, dan pelatihan bagi 4 orang dosen ToT.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Pelatihan ToT Dosen dan Ujian Sertifikasi Mahasiswa",
      pic: "Tengku M. Khairil, S.Kom., M.Kom.",
      location: "Lab Komputer GD 9 FITE IT Del",
      participantCount: 200,
      budget: 180000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "4 dosen bersertifikat instruktur HCIA dan 200 voucher sertifikasi terdistribusi.",
      expectedOutcome: "Integrasi modul industri Huawei ke mata kuliah Jaringan Komputer dan Cloud Computing.",
      actualOutput: "4 dosen tersertifikasi instruktur, modul terintegrasi di Semester Ganjil 2024/2025.",
      outcome: "Mahasiswa prodi Informatika dan TRPL mendapat akses materi terkini standar industri.",
      impact: "Pemenuhan IKU 1 (Lulusan Mendapat Pekerjaan Layak) dan IKU 2 (Mahasiswa Berkegiatan di Luar Kampus).",
      followUp: "Penyusunan jadwal bootcamp ujian gelombang ke-2.",
      status: "VALIDATED",
      confidenceScore: 0.96,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-01",
      extractedDate: "2024-06-11T09:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-06-12T14:15:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/PKS_Huawei_FITE_2024.pdf",
      fileName: "PKS_Huawei_FITE_2024.pdf",
      fileSize: "1.8 MB"
    },
    {
      id: "DOC-IA-2024-003",
      documentNumber: "IA/015/FITE-IF/IX/2024",
      title: "Implementation Arrangement Penyelenggaraan Ujian Sertifikasi HCIA Datacom Gelombang 1",
      type: "IA",
      partnerId: "PARTNER-001",
      partnerName: "PT Huawei Tech Investment",
      parentId: "DOC-PKS-2024-002",
      parentNumber: "028/ITDel/PKS/FITE/VI/2024",
      country: "Indonesia",
      partnerSignatoryName: "Rian Hidayat (Talent Manager)",
      partnerSignatoryPosition: "Ecosystem Operations Specialist",
      itDelSignatoryName: "Yusuf Kurniawan, S.T., M.Sc.",
      itDelSignatoryPosition: "Ketua Program Studi S1 Informatika",
      signedDate: "2024-09-02",
      effectiveStartDate: "2024-09-02",
      effectiveEndDate: "2024-12-20",
      scope: "Pelaksanaan mock exam, pendaftaran akun Pearson VUE, dan pelaksanaan proctored exam bagi 60 mahasiswa angkatan 2021.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Bootcamp dan Ujian HCIA Datacom 2024",
      pic: "Ronal M. Panjaitan, S.Kom., M.T.",
      location: "Auditorium & Ruang CBT IT Del",
      participantCount: 60,
      budget: 45000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "Tingkat kelulusan di atas 80% dari total 60 peserta.",
      expectedOutcome: "Sertifikat resmi bertaraf global untuk portofolio SKPI mahasiswa.",
      actualOutput: "54 mahasiswa dinyatakan LULUS (Passing rate 90%).",
      outcome: "Semua peserta lulus menerima sertifikat digital yang terverifikasi di portal Huawei.",
      impact: "Mendongkrak data capaian sertifikasi kompetensi mahasiswa untuk akreditasi LAM-INFOKOM.",
      followUp: "Penyerahan sertifikat fisik dan pemutakhiran data SKPI di BAAK.",
      status: "VALIDATED",
      confidenceScore: 0.95,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 2,
      batchId: "SEED-BATCH-01",
      extractedDate: "2024-09-03T11:20:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-09-05T09:10:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/IA_Huawei_Datacom_2024.pdf",
      fileName: "IA_Huawei_Datacom_2024.pdf",
      fileSize: "1.2 MB"
    },
    {
      id: "DOC-PROP-2024-004",
      documentNumber: "PROP/IF-2024/008",
      title: "Proposal Pengajuan Hibah Riset Bersama: Pengembangan Intelligent Edge Sensing untuk Danau Toba",
      type: "PROPOSAL",
      partnerId: "PARTNER-001",
      partnerName: "PT Huawei Tech Investment",
      parentId: "DOC-IA-2024-003",
      parentNumber: "IA/015/FITE-IF/IX/2024",
      country: "Indonesia",
      partnerSignatoryName: "Tim Seleksi R&D Huawei Indonesia",
      partnerSignatoryPosition: "R&D Grant Evaluation Committee",
      itDelSignatoryName: "Yusuf Kurniawan, S.T., M.Sc.",
      itDelSignatoryPosition: "Ketua Tim Peneliti IT Del",
      signedDate: "2024-10-15",
      effectiveStartDate: "2024-11-01",
      effectiveEndDate: "2025-06-30",
      scope: "Pengembangan sensor IoT berbasis 5G Narrowband untuk monitoring kualitas air Danau Toba dan mitigasi eceng gondok.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-LPPM",
      triDharma: "RESEARCH",
      activityName: "Riset IoT & AI Edge Computing Perairan Toba",
      pic: "Indra H. M. Saragih, S.T., M.T.",
      location: "Dermaga Sitoluama & Lab Jaringan IT Del",
      participantCount: 8,
      budget: 120000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "1 purwarupa sensor pelampung IoT dan 1 draf publikasi Scopus Q2.",
      expectedOutcome: "Sistem monitoring real-time berbasis dasbor web.",
      actualOutput: "Purwarupa sensor selesai 85%, terpasang di stasiun uji coba Danau Toba.",
      outcome: "Data telemetri berhasil terkirim ke server kampus setiap 15 menit.",
      impact: "Mendukung program prioritas nasional Danau Toba sebagai Destinasi Pariwisata Super Prioritas (DPSP).",
      followUp: "Penyusunan laporan kemajuan semester genap.",
      status: "VALIDATED",
      confidenceScore: 0.94,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 2,
      batchId: "SEED-BATCH-01",
      extractedDate: "2024-10-16T15:00:00Z",
      validatedBy: "Kepala Biro Kemitraan",
      validatedDate: "2024-10-18T10:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/Proposal_IoT_Toba_Huawei.pdf",
      fileName: "Proposal_IoT_Toba_Huawei.pdf",
      fileSize: "3.1 MB"
    },
    {
      id: "DOC-REP-2025-005",
      documentNumber: "LPJ/IF-2025/002",
      title: "Laporan Pelaksanaan Akhir: Ujian Sertifikasi HCIA Datacom dan Evaluasi Hasil Pembelajaran",
      type: "FINAL_REPORT",
      partnerId: "PARTNER-001",
      partnerName: "PT Huawei Tech Investment",
      parentId: "DOC-PROP-2024-004",
      parentNumber: "PROP/IF-2024/008",
      country: "Indonesia",
      partnerSignatoryName: "Budi Santoso, Ph.D.",
      partnerSignatoryPosition: "Director of ICT Talent Ecosystem",
      itDelSignatoryName: "Yusuf Kurniawan, S.T., M.Sc.",
      itDelSignatoryPosition: "Ketua Pelaksana Program",
      signedDate: "2025-01-20",
      effectiveStartDate: "2024-09-02",
      effectiveEndDate: "2024-12-20",
      scope: "Laporan pertanggungjawaban dana, rekapitulasi nilai ujian, evaluasi kepuasan peserta, dan serah terima data sertifikat.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Final Report Ujian Sertifikasi Gelombang 1",
      pic: "Ronal M. Panjaitan, S.Kom., M.T.",
      location: "Kampus IT Del",
      participantCount: 60,
      budget: 45000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "Laporan LPJ lengkap dengan rekap skor dan kuitansi pertanggungjawaban.",
      expectedOutcome: "Diterimanya LPJ oleh pihak Huawei Indonesia tanpa catatan revisi.",
      actualOutput: "Dokumen LPJ 48 halaman disetujui penuh oleh Huawei dan UKS IT Del.",
      outcome: "IT Del terpilih sebagai Finalis Best Huawei Academy Indonesia 2024.",
      impact: "Mendapat prioritas penambahan kuota voucher ujian untuk tahun anggaran 2025/2026.",
      followUp: "Pengajuan proposal lanjutan untuk sertifikasi AI dan Cloud Security.",
      status: "VALIDATED",
      confidenceScore: 0.99,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 4,
      batchId: "SEED-BATCH-01",
      extractedDate: "2025-01-22T08:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2025-01-25T11:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/LPJ_Huawei_Datacom_2024.pdf",
      fileName: "LPJ_Huawei_Datacom_2024.pdf",
      fileSize: "4.5 MB"
    },
    {
      id: "DOC-MOU-2023-006",
      documentNumber: "005/ITDel/MoU/VIII/2023",
      title: "Nota Kesepahaman Kolaborasi Tri Dharma Perguruan Tinggi, Beasiswa dan Rekrutmen Talenta",
      type: "MOU_LOI",
      partnerId: "PARTNER-002",
      partnerName: "PT Astra International Tbk",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Djony Bunarto Tjondro",
      partnerSignatoryPosition: "Presiden Direktur",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2023-08-25",
      effectiveStartDate: "2023-08-25",
      effectiveEndDate: "2028-08-24",
      scope: "Program beasiswa mahasiswa berprestasi dari keluarga prasejahtera, program magang MBKM di anak perusahaan grup Astra, serta kuliah tamu berkala pimpinan Astra.",
      facultyId: "FTI",
      studyProgramId: "PRODI-MR",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Program Beasiswa Astra & Magang MBKM Industri",
      pic: "Humasak T. A. Simanjuntak, S.T., M.ISD.",
      location: "Laguboti & Jakarta",
      participantCount: 45,
      budget: 850000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "Penyaluran beasiswa SPP dan biaya hidup bagi 30 mahasiswa terpilih setiap tahun.",
      expectedOutcome: "Tingkat kelulusan tepat waktu mahasiswa penerima beasiswa 100%.",
      actualOutput: "60 mahasiswa telah menerima manfaat beasiswa (2023-2025).",
      outcome: "22 penerima beasiswa langsung diterima bekerja di Grup Astra setelah lulus.",
      impact: "Mendongkrak indikator keterjangkauan pendidikan tinggi di kawasan Danau Toba.",
      followUp: "Monitoring evaluasi IPK semesteran mahasiswa penerima beasiswa.",
      status: "VALIDATED",
      confidenceScore: 0.97,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-02",
      extractedDate: "2023-08-26T10:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2023-08-28T16:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_Astra_ITDel_2023.pdf",
      fileName: "MOU_Astra_ITDel_2023.pdf",
      fileSize: "2.1 MB"
    },
    {
      id: "DOC-PKS-2024-007",
      documentNumber: "019/ITDel/PKS/FTI/V/2024",
      title: "Perjanjian Kerja Sama Magang Bersertifikat Industri dan Proyek Capstone Manajemen Rekayasa",
      type: "PKS_MOA",
      partnerId: "PARTNER-002",
      partnerName: "PT Astra International Tbk",
      parentId: "DOC-MOU-2023-006",
      parentNumber: "005/ITDel/MoU/VIII/2023",
      country: "Indonesia",
      partnerSignatoryName: "Ratna Sari Dewi",
      partnerSignatoryPosition: "Head of CSR & Education Support",
      itDelSignatoryName: "Dr. Rizal Sinaga, S.T., M.T.",
      itDelSignatoryPosition: "Dekan Fakultas Teknologi Industri",
      signedDate: "2024-05-14",
      effectiveStartDate: "2024-05-14",
      effectiveEndDate: "2026-05-13",
      scope: "Penempatan magang 6 bulan bagi 15 mahasiswa S1 Manajemen Rekayasa di pabrik manufaktur Grup Astra dan pembimbingan capstone project.",
      facultyId: "FTI",
      studyProgramId: "PRODI-MR",
      internalUnitId: "UNIT-CDC",
      triDharma: "EDUCATION",
      activityName: "Magang Capstone Project Manufaktur Astra",
      pic: "Yanti N. Simamora, S.T., M.Sc.",
      location: "Plant Astra Daihatsu Sunter / Karawang",
      participantCount: 15,
      budget: 150000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "15 laporan magang komprehensif dan 3 solusi optimasi proses manufaktur.",
      expectedOutcome: "Konversi 20 SKS mata kuliah magang MBKM tanpa kendala.",
      actualOutput: "15 mahasiswa menyelesaikan magang dengan predikat Sangat Baik (A).",
      outcome: "2 proyek perbaikan efisiensi lini produksi diimplementasikan di pabrik Astra.",
      impact: "Mendukung akreditasi IABEE program studi Manajemen Rekayasa.",
      followUp: "Pembukaan pendaftaran gelombang magang semester ganjil 2026.",
      status: "VALIDATED",
      confidenceScore: 0.95,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 2,
      batchId: "SEED-BATCH-02",
      extractedDate: "2024-05-15T14:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-05-18T10:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/PKS_Astra_FTI_2024.pdf",
      fileName: "PKS_Astra_FTI_2024.pdf",
      fileSize: "1.9 MB"
    },
    {
      id: "DOC-PKS-2026-008",
      documentNumber: "007/ITDel/PKS/FITE/I/2026",
      title: "Perjanjian Kerja Sama Riset Terapan Kecerdasan Buatan untuk Otomasi Pemantauan Industri 2026",
      type: "PKS_MOA",
      partnerId: "PARTNER-002",
      partnerName: "PT Astra International Tbk",
      parentId: "DOC-MOU-2023-006",
      parentNumber: "005/ITDel/MoU/VIII/2023",
      country: "Indonesia",
      partnerSignatoryName: "Hendrik Gunawan (Head of R&D Digital)",
      partnerSignatoryPosition: "Chief of Innovation & Technology",
      itDelSignatoryName: "Dr. Johannes Harungguan Sianipar, S.T., M.T.",
      itDelSignatoryPosition: "Dekan FITE",
      signedDate: "2026-01-12",
      effectiveStartDate: "2026-01-12",
      effectiveEndDate: "2027-01-11",
      scope: "Riset bersama machine vision untuk quality control suku cadang otomotif di lini perakitan.",
      facultyId: "FITE",
      studyProgramId: "PRODI-TE",
      internalUnitId: "UNIT-LPPM",
      triDharma: "RESEARCH",
      activityName: "Joint Research Machine Vision Otomotif",
      pic: "Indra H. M. Saragih, S.T., M.T.",
      location: "Lab Visi Komputer IT Del & Astra Tech Center",
      participantCount: 12,
      budget: 275000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "Model deteksi cacat visual akurasi >98% dan 1 paten terdaftar.",
      expectedOutcome: "Pengurangan waktu inspeksi manual di lini perakitan hingga 40%.",
      actualOutput: "Dataset 10.000 citra telah terkumpul, model baseline akurasi 94.2%.",
      outcome: "Paper ilmiah diterima di konferensi IEEE TENCON 2026.",
      impact: "Meningkatkan citra riset terapan IT Del bersama industri manufaktur nasional.",
      followUp: "Uji coba running prototipe di line 2 pabrik perakitan pada Triwulan III.",
      status: "VALIDATED",
      confidenceScore: 0.98,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-02",
      extractedDate: "2026-01-14T11:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2026-01-16T15:30:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/PKS_Astra_Riset_2026.pdf",
      fileName: "PKS_Astra_Riset_2026.pdf",
      fileSize: "2.3 MB"
    },
    {
      id: "DOC-MOU-2025-009",
      documentNumber: "003/ITDel/MoU/II/2025",
      title: "Nota Kesepahaman Akselerasi Keterampilan AI Mahasiswa dan Pemanfaatan Platform Cloud Azure",
      type: "MOU_LOI",
      partnerId: "PARTNER-003",
      partnerName: "PT Microsoft Indonesia",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Dharma Simorangkir",
      partnerSignatoryPosition: "President Director",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2025-02-20",
      effectiveStartDate: "2025-02-20",
      effectiveEndDate: "2028-02-19",
      scope: "Akses program Microsoft Learn for Educators, beasiswa sertifikasi Azure AI Fundamentals (AI-900), dan workshop GenAI Copilot untuk dosen dan mahasiswa.",
      facultyId: "FITE",
      studyProgramId: "PRODI-SI",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Microsoft AI Skills Academy & Azure Credits",
      pic: "Tengku M. Khairil, S.Kom., M.Kom.",
      location: "Kampus IT Del, Laguboti",
      participantCount: 250,
      budget: 500000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "250 mahasiswa terlatih modul Generative AI dan 100 orang tersertifikasi AI-900.",
      expectedOutcome: "Dosen mengintegrasikan studi kasus AI terkini dalam perkuliahan SI.",
      actualOutput: "180 mahasiswa telah menyelesaikan learning path, 74 lulus sertifikasi.",
      outcome: "Laboratorium sistem informasi dilengkapi akun Azure Dev Tools terverifikasi.",
      impact: "Mendukung indikator IKU akreditasi BAN-PT terkait kemitraan dengan industri global.",
      followUp: "Penyusunan PKS turunan untuk hackathon AI solusi daerah Danau Toba.",
      status: "VALIDATED",
      confidenceScore: 0.97,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 2,
      batchId: "SEED-BATCH-03",
      extractedDate: "2025-02-21T09:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2025-02-23T11:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_Microsoft_ITDel_2025.pdf",
      fileName: "MOU_Microsoft_ITDel_2025.pdf",
      fileSize: "2.8 MB"
    },
    {
      id: "DOC-PKS-2025-010",
      documentNumber: "014/ITDel/PKS/FITE/VI/2025",
      title: "Perjanjian Kerja Sama Hackathon AI for Lake Toba Sustainable Tourism and Ecology",
      type: "PKS_MOA",
      partnerId: "PARTNER-003",
      partnerName: "PT Microsoft Indonesia",
      parentId: "DOC-MOU-2025-009",
      parentNumber: "003/ITDel/MoU/II/2025",
      country: "Indonesia",
      partnerSignatoryName: "Dian Astuti",
      partnerSignatoryPosition: "Education Industry Lead",
      itDelSignatoryName: "Dr. Johannes Harungguan Sianipar, S.T., M.T.",
      itDelSignatoryPosition: "Dekan FITE",
      signedDate: "2025-06-18",
      effectiveStartDate: "2025-06-18",
      effectiveEndDate: "2026-06-17",
      scope: "Kompetisi pengembangan aplikasi AI pariwisata ramah lingkungan berbasis Azure OpenAI Service dengan hadiah pembinaan dan kesempatan mentoring inkubator.",
      facultyId: "FITE",
      studyProgramId: "PRODI-TRPL",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Hackathon AI Toba 2025",
      pic: "Ronal M. Panjaitan, S.Kom., M.T.",
      location: "Gedung Serba Guna IT Del & Online",
      participantCount: 120,
      budget: 85000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "3 tim juara dengan prototipe siap uji dan 1 prototipe diadopsi Pemda.",
      expectedOutcome: "Peningkatan motivasi riset terapan mahasiswa di bidang GenAI.",
      actualOutput: "28 tim berkompetisi, 3 aplikasi terbaik diluncurkan di portal Pemkab.",
      outcome: "Aplikasi 'TobaSmartTour' diujicobakan pada festival Danau Toba.",
      impact: "Membawa nama IT Del di tingkat nasional sebagai kampus pionir AI di Sumatera.",
      followUp: "Inkubasi lanjutan tim juara bersama Microsoft Startups Program.",
      status: "VALIDATED",
      confidenceScore: 0.94,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-03",
      extractedDate: "2025-06-20T10:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2025-06-24T14:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/PKS_Microsoft_Hackathon_2025.pdf",
      fileName: "PKS_Microsoft_Hackathon_2025.pdf",
      fileSize: "1.7 MB"
    },
    {
      id: "DOC-MOU-2024-011",
      documentNumber: "008/ITDel/MoU/III/2024",
      title: "Nota Kesepahaman Pengembangan Ekosistem FinTech Kampus, Beasiswa Difabel, dan Rekrutmen",
      type: "MOU_LOI",
      partnerId: "PARTNER-004",
      partnerName: "PT Bank Mandiri (Persero) Tbk",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Daratmin Juwono (Regional CEO Mandiri Sumut)",
      partnerSignatoryPosition: "Regional CEO Region I / Sumatera 1",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2024-03-12",
      effectiveStartDate: "2024-03-12",
      effectiveEndDate: "2027-03-11",
      scope: "Penyediaan layanan perbankan digital Livin' Sukha untuk ekosistem kampus, beasiswa prestasi Mandiri, serta fasilitas sponsorship sarana kampus.",
      facultyId: "FTI",
      studyProgramId: "PRODI-MR",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "INSTITUTIONAL",
      activityName: "Mandiri Digital Smart Campus & Beasiswa Prestasi",
      pic: "Monika Siahaan, S.Sos.",
      location: "Kampus IT Del",
      participantCount: 50,
      budget: 400000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "Integrasi sistem pembayaran SPP terintegrasi virtual account Mandiri dan renovasi co-working space.",
      expectedOutcome: "Efisiensi rekonsiliasi keuangan kampus hingga 95% otomatis.",
      actualOutput: "Co-working space Mandiri Hub selesai dibangun dan dimanfaatkan mahasiswa.",
      outcome: "Kemudahan transaksi non-tunai di kantin dan koperasi kampus.",
      impact: "Peningkatan kepuasan mahasiswa atas fasilitas sarana dan prasarana kampus.",
      followUp: "Monitoring penggunaan co-working space dan beasiswa tahap 2.",
      status: "VALIDATED",
      confidenceScore: 0.98,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-03",
      extractedDate: "2024-03-14T08:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-03-16T10:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_Mandiri_ITDel_2024.pdf",
      fileName: "MOU_Mandiri_ITDel_2024.pdf",
      fileSize: "2.5 MB"
    },
    {
      id: "DOC-MOU-2023-012",
      documentNumber: "002/ITDel/MoU/I/2023",
      title: "Nota Kesepahaman Peningkatan Mutu Tri Dharma Perguruan Tinggi dan Pembinaan Program Pascasarjana",
      type: "MOU_LOI",
      partnerId: "PARTNER-005",
      partnerName: "Institut Teknologi Bandung",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Prof. Ir. N. R. Reini Wirahadikusumah, Ph.D.",
      partnerSignatoryPosition: "Rektor ITB",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2023-01-25",
      effectiveStartDate: "2023-01-25",
      effectiveEndDate: "2028-01-24",
      scope: "Bimbingan akreditasi internasional, pembinaan studi lanjut S3 dosen IT Del di ITB, penelitian kolaboratif antarfakultas, dan penguji bersama tugas akhir.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Bimbingan Dosen S3 dan Riset Kolaboratif ITB-IT Del",
      pic: "Humasak T. A. Simanjuntak, S.T., M.ISD.",
      location: "Bandung & Laguboti",
      participantCount: 20,
      budget: 200000000,
      fundingSource: "INTERNAL_DEL",
      expectedOutput: "5 dosen IT Del diterima program doktor di ITB dan 3 publikasi bersama.",
      expectedOutcome: "Kualifikasi dosen bergelar S3 meningkat signifikan untuk memenuhi standar akreditasi.",
      actualOutput: "4 dosen sedang menempuh S3 di STEI ITB, 2 makalah terbit di jurnal bereputasi.",
      outcome: "Peningkatan kualitas pembimbingan tugas akhir mahasiswa oleh dosen mitra.",
      impact: "Penguatan status akreditasi institusi IT Del di LLDIKTI Wilayah I.",
      followUp: "Penyelenggaraan simposium riset bersama tahun 2026.",
      status: "VALIDATED",
      confidenceScore: 0.99,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-04",
      extractedDate: "2023-01-26T10:00:00Z",
      validatedBy: "Kepala Biro Kemitraan",
      validatedDate: "2023-01-29T14:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_ITB_ITDel_2023.pdf",
      fileName: "MOU_ITB_ITDel_2023.pdf",
      fileSize: "2.0 MB"
    },
    {
      id: "DOC-PKS-2024-013",
      documentNumber: "011/ITDel/PKS/LPPM/IV/2024",
      title: "Perjanjian Kerja Sama Riset Kolaboratif Konsorsium Bioteknologi Pertanian Dataran Tinggi Toba",
      type: "PKS_MOA",
      partnerId: "PARTNER-005",
      partnerName: "Institut Teknologi Bandung",
      parentId: "DOC-MOU-2023-012",
      parentNumber: "002/ITDel/MoU/I/2023",
      country: "Indonesia",
      partnerSignatoryName: "Prof. Dr. I Nyoman P. Aryantha",
      partnerSignatoryPosition: "Dekan SITH ITB",
      itDelSignatoryName: "Dr. Merry M. Sibarani, S.Si., M.Si.",
      itDelSignatoryPosition: "Dekan Fakultas Bioteknologi",
      signedDate: "2024-04-05",
      effectiveStartDate: "2024-04-05",
      effectiveEndDate: "2026-04-04",
      scope: "Eksplorasi mikroba indigenous tanah Toba untuk pupuk hayati ramah lingkungan pada tanaman andaliman dan kopi arabika.",
      facultyId: "FB",
      studyProgramId: "PRODI-BP",
      internalUnitId: "UNIT-LPPM",
      triDharma: "RESEARCH",
      activityName: "Joint Research Bioteknologi Andaliman ITB-IT Del",
      pic: "Maria P. Hutapea, S.Si., M.Biotech.",
      location: "Lab Bioproses IT Del & Lab Mikrobiologi SITH ITB",
      participantCount: 14,
      budget: 160000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "Isolat bakteri unggul pelarut fosfat dan 1 publikasi jurnal internasional bereputasi.",
      expectedOutcome: "Formulasi pupuk hayati lokal untuk petani andaliman di Toba.",
      actualOutput: "3 isolat unggul teridentifikasi secara molekuler (16S rRNA sequencing).",
      outcome: "Peningkatan produktivitas bibit tanaman uji coba hingga 28%.",
      impact: "Mendukung komoditas unggulan lokal Sumatera Utara berbasis sains modern.",
      followUp: "Uji lapang skala percontohan di kebun petani mitra.",
      status: "VALIDATED",
      confidenceScore: 0.96,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 3,
      batchId: "SEED-BATCH-04",
      extractedDate: "2024-04-07T12:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-04-09T10:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/PKS_ITB_Bioproses_2024.pdf",
      fileName: "PKS_ITB_Bioproses_2024.pdf",
      fileSize: "2.1 MB"
    },
    {
      id: "DOC-MOU-2024-014",
      documentNumber: "009/ITDel/MoU/V/2024",
      title: "Nota Kesepahaman Sinergi Program Pemberdayaan Masyarakat, Smart Regency, dan Tata Kelola Digital",
      type: "MOU_LOI",
      partnerId: "PARTNER-006",
      partnerName: "Pemerintah Kabupaten Toba",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Poltak Sitorus",
      partnerSignatoryPosition: "Bupati Toba",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2024-05-02",
      effectiveStartDate: "2024-05-02",
      effectiveEndDate: "2029-05-01",
      scope: "Pendampingan penyusunan Masterplan Smart City Toba, sistem informasi e-retribusi objek wisata, serta pelatihan literasi digital aparatur desa.",
      facultyId: "FITE",
      studyProgramId: "PRODI-SI",
      internalUnitId: "UNIT-LPPM",
      triDharma: "COMMUNITY_SERVICE",
      activityName: "Smart Regency & Pengabdian Masyarakat Toba",
      pic: "Tengku M. Khairil, S.Kom., M.Kom.",
      location: "Balige & Laguboti, Kab. Toba",
      participantCount: 80,
      budget: 150000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "Dokumen Masterplan Smart City dan 5 desa wisata berbasis web profil digital.",
      expectedOutcome: "Peningkatan indeks SPBE (Sistem Pemerintahan Berbasis Elektronik) Pemkab Toba.",
      actualOutput: "Aplikasi e-retribusi pantai Lumban Silintong beroperasi, 30 staf desa terlatih.",
      outcome: "PAD retribusi wisata meningkat 35% karena transparansi pembayaran QRIS.",
      impact: "Mendongkrak indikator Pengabdian kepada Masyarakat (PkM) terapan berefek langsung.",
      followUp: "Perluasan sistem ke 4 objek wisata lainnya di kawasan Danau Toba.",
      status: "VALIDATED",
      confidenceScore: 0.98,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 4,
      batchId: "SEED-BATCH-05",
      extractedDate: "2024-05-04T10:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-05-06T15:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_Pemkab_Toba_2024.pdf",
      fileName: "MOU_Pemkab_Toba_2024.pdf",
      fileSize: "3.4 MB"
    },
    {
      id: "DOC-PKS-2024-015",
      documentNumber: "022/ITDel/PKS/FB/VII/2024",
      title: "Perjanjian Kerja Sama Penerapan Teknologi Pengomposan Sampah Organik Pasar Tradisional Balige",
      type: "PKS_MOA",
      partnerId: "PARTNER-006",
      partnerName: "Pemerintah Kabupaten Toba",
      parentId: "DOC-MOU-2024-014",
      parentNumber: "009/ITDel/MoU/V/2024",
      country: "Indonesia",
      partnerSignatoryName: "dr. Tommy Pardede (Kepala Dinas Lingkungan Hidup Toba)",
      partnerSignatoryPosition: "Kepala Dinas Lingkungan Hidup",
      itDelSignatoryName: "Dr. Merry M. Sibarani, S.Si., M.Si.",
      itDelSignatoryPosition: "Dekan Fakultas Bioteknologi",
      signedDate: "2024-07-16",
      effectiveStartDate: "2024-07-16",
      effectiveEndDate: "2025-07-15",
      scope: "Pembangunan instalasi biodigester dan komposter aerobik di Tempat Pemrosesan Sampah (TPS3R) Balige dengan starter bioaktivator formulasi IT Del.",
      facultyId: "FB",
      studyProgramId: "PRODI-BP",
      internalUnitId: "UNIT-LPPM",
      triDharma: "COMMUNITY_SERVICE",
      activityName: "Pengolahan Sampah Pasar Tradisional Balige",
      pic: "Maria P. Hutapea, S.Si., M.Biotech.",
      location: "TPS3R Balige, Kab. Toba",
      participantCount: 25,
      budget: 65000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "Unit komposter beroperasi dan menghasilkan 500 kg pupuk organik per bulan.",
      expectedOutcome: "Pengurangan volume sampah organik yang masuk ke TPA sebesar 40%.",
      actualOutput: "Instalasi selesai, pupuk cair dan padat telah dibagikan kepada kelompok tani binaan.",
      outcome: "Petani menghemat biaya pembelian pupuk sintetis sebesar 25%.",
      impact: "Mendapat apresiasi dari Kementerian LHK atas kolaborasi kampus-daerah.",
      followUp: "Monitoring kualitas mutu pupuk kompos berkala setiap 3 bulan.",
      status: "VALIDATED",
      confidenceScore: 0.94,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 2,
      batchId: "SEED-BATCH-05",
      extractedDate: "2024-07-18T11:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2024-07-20T16:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/PKS_Pemkab_TPS3R_2024.pdf",
      fileName: "PKS_Pemkab_TPS3R_2024.pdf",
      fileSize: "1.6 MB"
    },
    {
      id: "DOC-MOU-2024-016",
      documentNumber: "015/ITDel/MoU/X/2024",
      title: "Memorandum of Understanding on Academic Student Exchange, Summer Immersion and Cultural Exchange",
      type: "MOU_LOI",
      partnerId: "PARTNER-007",
      partnerName: "National University of Singapore",
      parentId: null,
      parentNumber: null,
      country: "Singapura",
      partnerSignatoryName: "Prof. Aaron Tan",
      partnerSignatoryPosition: "Director of International Relations",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2024-10-08",
      effectiveStartDate: "2024-10-08",
      effectiveEndDate: "2027-10-07",
      scope: "Student immersion trip, credit-bearing summer workshops on IoT & Data Science, joint cultural exchange programs in Toba Lake region.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "NUS-IT Del STEER Summer Immersion Program",
      pic: "Humasak T. A. Simanjuntak, S.T., M.ISD.",
      location: "Singapore & Laguboti",
      participantCount: 35,
      budget: 320000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "Pertukaran 20 mahasiswa NUS ke Toba dan 5 mahasiswa IT Del ke kampus NUS Singapore.",
      expectedOutcome: "Wawasan global dan kemampuan bahasa Inggris mahasiswa meningkat pesat.",
      actualOutput: "Kunjungan 22 mahasiswa NUS selesai terlaksana di bulan Desember 2024.",
      outcome: "Proyek kolaborasi prototipe pemantauan lingkungan air berhasil dipresentasikan.",
      impact: "Mendukung pemenuhan IKU Kerjasama Internasional untuk Akreditasi Institusi.",
      followUp: "Seleksi calon mahasiswa IT Del untuk program balasan ke NUS bulan Juli 2026.",
      status: "VALIDATED",
      confidenceScore: 0.99,
      qualityFlags: [],
      hasEvidence: true,
      evidenceCount: 4,
      batchId: "SEED-BATCH-06",
      extractedDate: "2024-10-10T09:00:00Z",
      validatedBy: "Kepala Biro Kemitraan",
      validatedDate: "2024-10-14T11:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_NUS_ITDel_2024.pdf",
      fileName: "MOU_NUS_ITDel_2024.pdf",
      fileSize: "2.7 MB"
    },
    {
      id: "DOC-ORPHAN-017",
      documentNumber: "041/ITDel/PKS/FITE/XI/2025",
      title: "Perjanjian Kerja Sama Magang dan Rekrutmen Pengembang Mobile App Flutter",
      type: "PKS_MOA",
      partnerId: "PARTNER-001",
      partnerName: "PT Huawei Tech Investment",
      parentId: null, // ORPHAN PKS (needs linking to MOU!)
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Andi Wijaya (Senior HR Talent)",
      partnerSignatoryPosition: "HR Talent Acquisition",
      itDelSignatoryName: "Dr. Johannes Harungguan Sianipar, S.T., M.T.",
      itDelSignatoryPosition: "Dekan FITE",
      signedDate: "2025-11-10",
      effectiveStartDate: "2025-11-10",
      effectiveEndDate: "2026-11-09",
      scope: "Penyaluran 10 mahasiswa magang pengembang mobile HMS (Huawei Mobile Services).",
      facultyId: "FITE",
      studyProgramId: "PRODI-TRPL",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "EDUCATION",
      activityName: "Magang HMS Flutter Mobile Developer",
      pic: "Ronal M. Panjaitan, S.Kom., M.T.",
      location: "Jakarta & Hybrid",
      participantCount: 10,
      budget: 60000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "10 mahasiswa magang menyelesaikan 2 aplikasi berbasis Huawei Mobile Service.",
      expectedOutcome: "Peluang penawaran kontrak kerja sebelum wisuda.",
      actualOutput: "Mahasiswa sedang menjalani masa magang bulan ke-4.",
      outcome: "1 aplikasi telah terbit di Huawei AppGallery.",
      impact: "Meningkatkan portofolio mahasiswa D4 TRPL.",
      followUp: "Tautkan dokumen ini ke Nota Kesepahaman Induk (DOC-MOU-2024-001).",
      status: "NEEDS_REVIEW",
      confidenceScore: 0.72,
      qualityFlags: ["orphan_pks", "pending_validation"],
      hasEvidence: false,
      evidenceCount: 0,
      batchId: "SEED-BATCH-07",
      extractedDate: "2025-11-12T14:20:00Z",
      validatedBy: null,
      validatedDate: null,
      officialDataConfirmed: false,
      fileUrl: "sample-docs/PKS_HMS_Flutter_2025.pdf",
      fileName: "PKS_HMS_Flutter_2025.pdf",
      fileSize: "1.4 MB"
    },
    {
      id: "DOC-EXPIRING-018",
      documentNumber: "001/ITDel/MoU/XI/2023",
      title: "Nota Kesepahaman Konservasi Kawasan Hutan dan Pendampingan Pertanian Organik Toba",
      type: "MOU_LOI",
      partnerId: "PARTNER-008",
      partnerName: "Yayasan Inovasi Teknologi Toba Lestari",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Martua Simatupang",
      partnerSignatoryPosition: "Ketua Pengurus Yayasan",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor Institut Teknologi Del",
      signedDate: "2023-11-20",
      effectiveStartDate: "2023-11-20",
      effectiveEndDate: "2026-11-19", // EXPIRING SOON in ~45 days based on simulated local date
      scope: "Pengembangan bibit pohon endemik Toba, pembuatan demplot pertanian organik, dan lokakarya lingkungan hidup.",
      facultyId: "FB",
      studyProgramId: "PRODI-BP",
      internalUnitId: "UNIT-LPPM",
      triDharma: "COMMUNITY_SERVICE",
      activityName: "Konservasi Hutan dan Demplot Organik",
      pic: "Maria P. Hutapea, S.Si., M.Biotech.",
      location: "Kecamatan Laguboti & Silaen",
      participantCount: 40,
      budget: 50000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "1 demplot pertanian organik dan penanaman 1.000 bibit pohon.",
      expectedOutcome: "Kesadaran masyarakat desa sekitar kampus terhadap konservasi lereng bukit.",
      actualOutput: "1.200 bibit tertanam dan tumbuh baik, demplot dikelola warga.",
      outcome: "Penurunan erosi permukaan tanah di area uji coba.",
      impact: "Mendukung kelestarian catchment area Danau Toba.",
      followUp: "Perlu dibuat addendum perpanjangan waktu kerja sama atau evaluasi penutupan.",
      status: "VALIDATED",
      confidenceScore: 0.93,
      qualityFlags: ["expiring_soon"],
      hasEvidence: true,
      evidenceCount: 1,
      batchId: "SEED-BATCH-08",
      extractedDate: "2023-11-22T10:00:00Z",
      validatedBy: "Staff Unit Kerja Sama",
      validatedDate: "2023-11-25T14:00:00Z",
      officialDataConfirmed: true,
      fileUrl: "sample-docs/MOU_Yayasan_Toba_2023.pdf",
      fileName: "MOU_Yayasan_Toba_2023.pdf",
      fileSize: "1.9 MB"
    },
    {
      id: "DOC-AI-SAMPLE-019",
      documentNumber: "002/ITDel/MoU/III/2026",
      title: "Nota Kesepahaman Pengembangan Laboratorium Inovasi Semikonduktor dan Rekayasa Material Canggih",
      type: "MOU_LOI",
      partnerId: "PARTNER-002",
      partnerName: "PT Astra International Tbk",
      parentId: null,
      parentNumber: null,
      country: "Indonesia",
      partnerSignatoryName: "Gita Tiffany (Director Human Capital Astra)",
      partnerSignatoryPosition: "Chief of Human Capital & Sustainability",
      itDelSignatoryName: "Dr. Arnaldo Marulitua Sinaga, S.T., M.InfoTech.",
      itDelSignatoryPosition: "Rektor IT Del",
      signedDate: "2026-03-01",
      effectiveStartDate: "2026-03-01",
      effectiveEndDate: "2031-02-28",
      scope: "Pendirian Astra Advanced Materials Corner di Fakultas Teknologi Industri, pertukaran pakar manufaktur, dan riset terapan pengujian logam lokal.",
      facultyId: "FTI",
      studyProgramId: "PRODI-MT",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "RESEARCH",
      activityName: "Pendirian Astra Material Science Center",
      pic: "David H. Marpaung, S.T., M.T.",
      location: "Gedung Laboratorium Terpadu IT Del",
      participantCount: 50,
      budget: 650000000,
      fundingSource: "PARTNER_GRANT",
      expectedOutput: "1 fasilitas laboratorium karakterisasi logam dan 2 riset bersama terbit di prosiding internasional.",
      expectedOutcome: "Mahasiswa Teknik Metalurgi memiliki akses ke instrumen uji mutakhir.",
      actualOutput: "Nota kesepahaman baru saja ditandatangani.",
      outcome: "Perencanaan tata letak ruangan laboratorium sedang difinalisasi.",
      impact: "Mempersiapkan pendirian pusat unggulan rekayasa material di Sumatera Utara.",
      followUp: "Penyusunan Perjanjian Kerja Sama teknis pengadaan instrumen.",
      status: "AI_EXTRACTED",
      confidenceScore: 0.88,
      qualityFlags: ["pending_validation"],
      hasEvidence: false,
      evidenceCount: 0,
      batchId: "SEED-BATCH-09",
      extractedDate: "2026-03-05T09:15:00Z",
      validatedBy: null,
      validatedDate: null,
      officialDataConfirmed: false,
      fileUrl: "sample-docs/MOU_Astra_Material_2026.pdf",
      fileName: "MOU_Astra_Material_2026.pdf",
      fileSize: "2.6 MB"
    },
    {
      id: "DOC-AI-SAMPLE-020",
      documentNumber: "005/ITDel/PKS/FITE/III/2026",
      title: "Perjanjian Kerja Sama Pembangunan Smart Classroom dan Hybrid Collaborative Workspace",
      type: "PKS_MOA",
      partnerId: "PARTNER-004",
      partnerName: "PT Bank Mandiri (Persero) Tbk",
      parentId: "DOC-MOU-2024-011",
      parentNumber: "008/ITDel/MoU/III/2024",
      country: "Indonesia",
      partnerSignatoryName: "Agus Pratama",
      partnerSignatoryPosition: "Senior Vice President Digital Banking",
      itDelSignatoryName: "Dr. Johannes Harungguan Sianipar, S.T., M.T.",
      itDelSignatoryPosition: "Dekan FITE",
      signedDate: "2026-03-15",
      effectiveStartDate: "2026-03-15",
      effectiveEndDate: "2028-03-14",
      scope: "Fasilitasi smart screen interactive, kamera auto-tracking, sound system kelas hybrid, serta lisensi kolaborasi digital.",
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      internalUnitId: "UNIT-KERJASAMA",
      triDharma: "INSTITUTIONAL",
      activityName: "Mandiri Smart Classroom Initiative 2026",
      pic: "Humasak T. A. Simanjuntak, S.T., M.ISD.",
      location: "Gedung Kuliah 7 IT Del",
      participantCount: 80,
      budget: 320000000,
      fundingSource: "CSR_AND_INTERNAL",
      expectedOutput: "2 ruang kuliah cerdas siap pakai untuk kelas paralel dan seminar internasional.",
      expectedOutcome: "Peningkatan kualitas audio-visual kuliah jarak jauh bagi mahasiswa dan dosen tamu.",
      actualOutput: "Peralatan elektronik sedang dalam proses instalasi dan kalibrasi.",
      outcome: "Uji coba perdana untuk kuliah tamu praktisi berhasil dengan lancar.",
      impact: "Mendongkrak kepuasan sarana perkuliahan standar internasional.",
      followUp: "Peresmian ruang kelas oleh Rektor IT Del dan Direksi Bank Mandiri.",
      status: "NEEDS_REVIEW",
      confidenceScore: 0.89,
      qualityFlags: ["pending_validation"],
      hasEvidence: false,
      evidenceCount: 0,
      batchId: "SEED-BATCH-09",
      extractedDate: "2026-03-18T14:30:00Z",
      validatedBy: null,
      validatedDate: null,
      officialDataConfirmed: false,
      fileUrl: "sample-docs/PKS_Mandiri_SmartClass_2026.pdf",
      fileName: "PKS_Mandiri_SmartClass_2026.pdf",
      fileSize: "2.1 MB"
    }
  ],
  activities: [
    {
      id: "ACT-001",
      documentId: "DOC-PKS-2024-002",
      documentNumber: "028/ITDel/PKS/FITE/VI/2024",
      partnerName: "PT Huawei Tech Investment",
      triDharma: "EDUCATION",
      title: "Bootcamp dan Ujian HCIA Datacom 2024",
      startDate: "2024-09-02",
      endDate: "2024-11-30",
      pic: "Ronal M. Panjaitan, S.Kom., M.T.",
      participantCount: 60,
      facultyId: "FITE",
      studyProgramId: "PRODI-IF",
      budget: 45000000,
      status: "COMPLETED",
      outputCount: 1,
      outcomeCount: 1,
      impactScore: "HIGH",
      evidenceIds: ["EVI-001", "EVI-002"]
    },
    {
      id: "ACT-002",
      documentId: "DOC-PKS-2024-007",
      documentNumber: "019/ITDel/PKS/FTI/V/2024",
      partnerName: "PT Astra International Tbk",
      triDharma: "EDUCATION",
      title: "Magang Capstone Project Manufaktur Astra",
      startDate: "2024-06-01",
      endDate: "2024-12-05",
      pic: "Yanti N. Simamora, S.T., M.Sc.",
      participantCount: 15,
      facultyId: "FTI",
      studyProgramId: "PRODI-MR",
      budget: 150000000,
      status: "COMPLETED",
      outputCount: 3,
      outcomeCount: 2,
      impactScore: "VERY_HIGH",
      evidenceIds: ["EVI-003"]
    },
    {
      id: "ACT-003",
      documentId: "DOC-PKS-2026-008",
      documentNumber: "007/ITDel/PKS/FITE/I/2026",
      partnerName: "PT Astra International Tbk",
      triDharma: "RESEARCH",
      title: "Joint Research Machine Vision Otomotif",
      startDate: "2026-01-15",
      endDate: "2026-10-30",
      pic: "Indra H. M. Saragih, S.T., M.T.",
      participantCount: 12,
      facultyId: "FITE",
      studyProgramId: "PRODI-TE",
      budget: 275000000,
      status: "ONGOING",
      outputCount: 2,
      outcomeCount: 1,
      impactScore: "HIGH",
      evidenceIds: ["EVI-004"]
    },
    {
      id: "ACT-004",
      documentId: "DOC-PKS-2024-013",
      documentNumber: "011/ITDel/PKS/LPPM/IV/2024",
      partnerName: "Institut Teknologi Bandung",
      triDharma: "RESEARCH",
      title: "Joint Research Bioteknologi Andaliman ITB-IT Del",
      startDate: "2024-04-10",
      endDate: "2025-12-15",
      pic: "Maria P. Hutapea, S.Si., M.Biotech.",
      participantCount: 14,
      facultyId: "FB",
      studyProgramId: "PRODI-BP",
      budget: 160000000,
      status: "COMPLETED",
      outputCount: 2,
      outcomeCount: 1,
      impactScore: "HIGH",
      evidenceIds: ["EVI-005"]
    },
    {
      id: "ACT-005",
      documentId: "DOC-PKS-2024-015",
      documentNumber: "022/ITDel/PKS/FB/VII/2024",
      partnerName: "Pemerintah Kabupaten Toba",
      triDharma: "COMMUNITY_SERVICE",
      title: "Pengolahan Sampah Pasar Tradisional Balige (TPS3R)",
      startDate: "2024-08-01",
      endDate: "2025-07-01",
      pic: "Maria P. Hutapea, S.Si., M.Biotech.",
      participantCount: 25,
      facultyId: "FB",
      studyProgramId: "PRODI-BP",
      budget: 65000000,
      status: "ONGOING",
      outputCount: 1,
      outcomeCount: 1,
      impactScore: "MEDIUM",
      evidenceIds: ["EVI-006"]
    }
  ],
  evidences: [
    {
      id: "EVI-001",
      title: "Sertifikat HCIA Datacom 54 Mahasiswa Angkatan 2021",
      type: "CERTIFICATE",
      documentId: "DOC-PKS-2024-002",
      documentNumber: "028/ITDel/PKS/FITE/VI/2024",
      activityId: "ACT-001",
      fileUrl: "sample-evidence/Sertifikat_HCIA_ITDel_2024.zip",
      fileName: "Sertifikat_HCIA_ITDel_2024.zip",
      fileSize: "18.2 MB",
      uploadedDate: "2024-12-22",
      uploadedBy: "Ronal M. Panjaitan",
      verified: true,
      verifiedBy: "SPM Unit",
      verifiedDate: "2025-01-05",
      mappedCriteria: ["LAM-INFOKOM C.1.4.a", "BAN-PT C.1.b"]
    },
    {
      id: "EVI-002",
      title: "Foto Dokumentasi dan Absensi Peserta Bootcamp Huawei",
      type: "PHOTO_ATTENDANCE",
      documentId: "DOC-PKS-2024-002",
      documentNumber: "028/ITDel/PKS/FITE/VI/2024",
      activityId: "ACT-001",
      fileUrl: "sample-evidence/Dokumentasi_Bootcamp_Huawei.pdf",
      fileName: "Dokumentasi_Bootcamp_Huawei.pdf",
      fileSize: "4.8 MB",
      uploadedDate: "2024-11-28",
      uploadedBy: "Ronal M. Panjaitan",
      verified: true,
      verifiedBy: "SPM Unit",
      verifiedDate: "2025-01-05",
      mappedCriteria: ["LAM-INFOKOM C.1.4.a"]
    },
    {
      id: "EVI-003",
      title: "Laporan Evaluasi Magang Industri Astra dan Surat Keterangan Penyelesaian",
      type: "REPORT_LETTER",
      documentId: "DOC-PKS-2024-007",
      documentNumber: "019/ITDel/PKS/FTI/V/2024",
      activityId: "ACT-002",
      fileUrl: "sample-evidence/Evaluasi_Magang_Astra_2024.pdf",
      fileName: "Evaluasi_Magang_Astra_2024.pdf",
      fileSize: "3.2 MB",
      uploadedDate: "2024-12-10",
      uploadedBy: "Yanti N. Simamora",
      verified: true,
      verifiedBy: "SPM Unit",
      verifiedDate: "2024-12-15",
      mappedCriteria: ["BAN-PT C.1.b", "LAM-TEKNIK 6.3"]
    },
    {
      id: "EVI-004",
      title: "Draf Publikasi Scopus dan Dataset Citra Cacat Produksi Logam",
      type: "PUBLICATION_DATASET",
      documentId: "DOC-PKS-2026-008",
      documentNumber: "007/ITDel/PKS/FITE/I/2026",
      activityId: "ACT-003",
      fileUrl: "sample-evidence/Draft_Scopus_Astra_ITDel_2026.pdf",
      fileName: "Draft_Scopus_Astra_ITDel_2026.pdf",
      fileSize: "2.9 MB",
      uploadedDate: "2026-02-18",
      uploadedBy: "Indra H. M. Saragih",
      verified: true,
      verifiedBy: "LPPM IT Del",
      verifiedDate: "2026-02-25",
      mappedCriteria: ["BAN-PT C.7.a", "LAM-INFOKOM C.7"]
    },
    {
      id: "EVI-005",
      title: "Publikasi Jurnal Internasional Hasil Isolasi Bakteri Andaliman",
      type: "JOURNAL_ARTICLE",
      documentId: "DOC-PKS-2024-013",
      documentNumber: "011/ITDel/PKS/LPPM/IV/2024",
      activityId: "ACT-004",
      fileUrl: "sample-evidence/Journal_Andaliman_ITB_ITDel.pdf",
      fileName: "Journal_Andaliman_ITB_ITDel.pdf",
      fileSize: "1.5 MB",
      uploadedDate: "2025-03-10",
      uploadedBy: "Maria P. Hutapea",
      verified: true,
      verifiedBy: "LPPM IT Del",
      verifiedDate: "2025-03-20",
      mappedCriteria: ["BAN-PT C.7.a", "BAN-PT C.1.b"]
    },
    {
      id: "EVI-006",
      title: "Berita Acara Uji Coba Bioaktivator dan Rekap Penyaluran Kompos TPS3R",
      type: "OFFICIAL_RECORD",
      documentId: "DOC-PKS-2024-015",
      documentNumber: "022/ITDel/PKS/FB/VII/2024",
      activityId: "ACT-005",
      fileUrl: "sample-evidence/BAST_TPS3R_Balige_2024.pdf",
      fileName: "BAST_TPS3R_Balige_2024.pdf",
      fileSize: "2.1 MB",
      uploadedDate: "2024-10-05",
      uploadedBy: "Maria P. Hutapea",
      verified: true,
      verifiedBy: "SPM Unit",
      verifiedDate: "2024-10-12",
      mappedCriteria: ["BAN-PT C.8.a"]
    }
  ],
  accreditationFrameworks: [
    {
      id: "BAN-PT-IAPS",
      name: "BAN-PT IAPS 4.0 / IAPT 3.0",
      organization: "Badan Akreditasi Nasional Perguruan Tinggi",
      description: "Instrumen Akreditasi Program Studi & Perguruan Tinggi dengan 9 Kriteria Utama.",
      indicators: [
        {
          id: "BANPT-C1-KERJASAMA",
          code: "C.1.b",
          criterion: "Kriteria 1 - Visi, Misi, Tujuan dan Strategi",
          name: "Kerja Sama Tri Dharma Perguruan Tinggi",
          targetScore: 4.0,
          requiredEvidence: "MoU/PKS aktif, bukti pelaksanaan kegiatan, dokumen implementasi dan dampak nyata bagi kemitraan.",
          linkedDocumentCount: 8,
          linkedEvidenceCount: 5,
          complianceStatus: "MET"
        },
        {
          id: "BANPT-C6-PENDIDIKAN",
          code: "C.6.a",
          criterion: "Kriteria 6 - Pendidikan",
          name: "Kurikulum & Keterlibatan Praktisi Industri",
          targetScore: 4.0,
          requiredEvidence: "PKS magang MBKM, SK dosen praktisi tamu industri, silabus terintegrasi sertifikasi kompetensi.",
          linkedDocumentCount: 5,
          linkedEvidenceCount: 3,
          complianceStatus: "MET"
        },
        {
          id: "BANPT-C7-PENELITIAN",
          code: "C.7.a",
          criterion: "Kriteria 7 - Penelitian",
          name: "Penelitian Bersama Mitra Nasional & Internasional",
          targetScore: 3.5,
          requiredEvidence: "PKS riset bersama, laporan kemajuan hibah riset, luaran publikasi atau paten berelasi.",
          linkedDocumentCount: 4,
          linkedEvidenceCount: 2,
          complianceStatus: "MET"
        },
        {
          id: "BANPT-C8-PENGMAS",
          code: "C.8.a",
          criterion: "Kriteria 8 - Pengabdian kepada Masyarakat",
          name: "Pemberdayaan Masyarakat Daerah Lingkar Kampus",
          targetScore: 3.5,
          requiredEvidence: "PKS dengan Pemda/Masyarakat, dokumentasi program TPS3R / digitalisasi desa, sertifikat kepuasan mitra.",
          linkedDocumentCount: 3,
          linkedEvidenceCount: 2,
          complianceStatus: "MET"
        }
      ]
    },
    {
      id: "LAM-INFOKOM",
      name: "LAM-INFOKOM (Informatika & Komputer)",
      organization: "Lembaga Akreditasi Mandiri Informatika dan Komputer",
      description: "Standar Akreditasi Khusus Program Studi Rumpun Ilmu Informatika & Komputer.",
      indicators: [
        {
          id: "LAM-INFO-C14A",
          code: "C.1.4.a",
          criterion: "Kriteria 1 - Tata Pamong & Kerja Sama",
          name: "Kerja Sama Bidang Pendidikan & Sertifikasi Kompetensi",
          targetScore: 4.0,
          requiredEvidence: "PKS Huawei Academy, Microsoft Learn, bukti ujian sertifikasi internasional mahasiswa.",
          linkedDocumentCount: 6,
          linkedEvidenceCount: 4,
          complianceStatus: "MET"
        },
        {
          id: "LAM-INFO-C14B",
          code: "C.1.4.b",
          criterion: "Kriteria 1 - Tata Pamong & Kerja Sama",
          name: "Kerja Sama Internasional Aktif",
          targetScore: 3.5,
          requiredEvidence: "MoU/IA dengan perguruan tinggi luar negeri bereputasi (contoh: NUS STEER program).",
          linkedDocumentCount: 2,
          linkedEvidenceCount: 1,
          complianceStatus: "MET"
        },
        {
          id: "LAM-INFO-C7",
          code: "C.7",
          criterion: "Kriteria 7 - Penelitian & Inovasi Perangkat Lunak",
          name: "Riset Terapan bersama Industri ICT",
          targetScore: 3.5,
          requiredEvidence: "Dokumen proposal dan luaran publikasi riset IoT & Edge sensing.",
          linkedDocumentCount: 2,
          linkedEvidenceCount: 1,
          complianceStatus: "MET"
        }
      ]
    }
  ],
  auditLogs: [
    {
      id: "AUDIT-001",
      timestamp: "2024-04-19T08:12:00Z",
      userRole: "ADMIN_STAFF",
      userName: "Staff Unit Kerja Sama",
      action: "DOCUMENT_UPLOADED",
      documentNumber: "012/ITDel/MoU/IV/2024",
      details: "Dokumen MoU Huawei Tech Investment diunggah via Batch Upload (SEED-BATCH-01)."
    },
    {
      id: "AUDIT-002",
      timestamp: "2024-04-19T08:12:05Z",
      userRole: "SYSTEM_AI",
      userName: "Deterministic Mock AI Engine",
      action: "AI_EXTRACTED",
      documentNumber: "012/ITDel/MoU/IV/2024",
      details: "Ekstraksi 26 metadata field selesai. Skor keyakinan rata-rata: 0.98. Status: AI_EXTRACTED."
    },
    {
      id: "AUDIT-003",
      timestamp: "2024-04-20T10:30:00Z",
      userRole: "ADMIN_STAFF",
      userName: "Staff Unit Kerja Sama",
      action: "STATUS_VALIDATED",
      documentNumber: "012/ITDel/MoU/IV/2024",
      details: "Pemeriksaan manusia selesai. Status disetujui sebagai data resmi: VALIDATED."
    },
    {
      id: "AUDIT-004",
      timestamp: "2024-06-12T14:15:00Z",
      userRole: "ADMIN_STAFF",
      userName: "Staff Unit Kerja Sama",
      action: "RELATIONSHIP_LINKED",
      documentNumber: "028/ITDel/PKS/FITE/VI/2024",
      details: "Dokumen ditautkan ke parent MoU: 012/ITDel/MoU/IV/2024 (PT Huawei Tech Investment)."
    },
    {
      id: "AUDIT-005",
      timestamp: "2025-01-25T11:00:00Z",
      userRole: "BUREAU_HEAD",
      userName: "Kepala Biro Kemitraan",
      action: "EVIDENCE_VERIFIED",
      documentNumber: "028/ITDel/PKS/FITE/VI/2024",
      details: "Verifikasi sertifikat HCIA Datacom (54 mahasiswa) dan LPJ Final selesai diperiksa."
    },
    {
      id: "AUDIT-006",
      timestamp: "2026-01-16T15:30:00Z",
      userRole: "ADMIN_STAFF",
      userName: "Staff Unit Kerja Sama",
      action: "DOCUMENT_VALIDATED",
      documentNumber: "007/ITDel/PKS/FITE/I/2026",
      details: "PKS Riset AI Astra 2026 divalidasi dan dihubungkan ke MoU Induk Astra 2023."
    }
  ]
};
